# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from app.generated_grpc import config_service_pb2 as config__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in config_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigurationServiceStub(object):
    """Описание gRPC-сервиса
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateConfiguration = channel.unary_unary(
                '/config.ConfigurationService/CreateConfiguration',
                request_serializer=config__service__pb2.CreateConfigRequest.SerializeToString,
                response_deserializer=config__service__pb2.CreateConfigResponse.FromString,
                _registered_method=True)
        self.SyncConfigurations = channel.unary_unary(
                '/config.ConfigurationService/SyncConfigurations',
                request_serializer=config__service__pb2.SyncConfigsRequest.SerializeToString,
                response_deserializer=config__service__pb2.SyncConfigsResponse.FromString,
                _registered_method=True)


class ConfigurationServiceServicer(object):
    """Описание gRPC-сервиса
    """

    def CreateConfiguration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncConfigurations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigurationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateConfiguration': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConfiguration,
                    request_deserializer=config__service__pb2.CreateConfigRequest.FromString,
                    response_serializer=config__service__pb2.CreateConfigResponse.SerializeToString,
            ),
            'SyncConfigurations': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncConfigurations,
                    request_deserializer=config__service__pb2.SyncConfigsRequest.FromString,
                    response_serializer=config__service__pb2.SyncConfigsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'config.ConfigurationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('config.ConfigurationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigurationService(object):
    """Описание gRPC-сервиса
    """

    @staticmethod
    def CreateConfiguration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.ConfigurationService/CreateConfiguration',
            config__service__pb2.CreateConfigRequest.SerializeToString,
            config__service__pb2.CreateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncConfigurations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/config.ConfigurationService/SyncConfigurations',
            config__service__pb2.SyncConfigsRequest.SerializeToString,
            config__service__pb2.SyncConfigsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
