# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'config_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63onfig_service.proto\x12\x06\x63onfig\"G\n\x13\x43reateConfigRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x0e\n\x06months\x18\x03 \x01(\x05\"S\n\x14\x43reateConfigResponse\x12\x13\n\x0b\x63onfig_link\x18\x01 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\x05\"%\n\x12SyncConfigsRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"&\n\x13SyncConfigsResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xb7\x01\n\x14\x43onfigurationService\x12P\n\x13\x43reateConfiguration\x12\x1b.config.CreateConfigRequest\x1a\x1c.config.CreateConfigResponse\x12M\n\x12SyncConfigurations\x12\x1a.config.SyncConfigsRequest\x1a\x1b.config.SyncConfigsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATECONFIGREQUEST']._serialized_start=32
  _globals['_CREATECONFIGREQUEST']._serialized_end=103
  _globals['_CREATECONFIGRESPONSE']._serialized_start=105
  _globals['_CREATECONFIGRESPONSE']._serialized_end=188
  _globals['_SYNCCONFIGSREQUEST']._serialized_start=190
  _globals['_SYNCCONFIGSREQUEST']._serialized_end=227
  _globals['_SYNCCONFIGSRESPONSE']._serialized_start=229
  _globals['_SYNCCONFIGSRESPONSE']._serialized_end=267
  _globals['_CONFIGURATIONSERVICE']._serialized_start=270
  _globals['_CONFIGURATIONSERVICE']._serialized_end=453
# @@protoc_insertion_point(module_scope)
