version: '3.8'

services:
  frontend:
    build:
      context: .  # Путь к вашему фронтенд-приложению
      dockerfile: client/vite.dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - flaskapp
    environment:
      - VITE_API_URL=http://flaskapp:4000  # окружение для Vite
    command: npm run dev
    networks:
      - app-network

  flaskapp:
    container_name: flaskapp
    build:
      context: . 
      dockerfile: server/flask.dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

volumes:
  pgdata: {}

networks:
  app-network:
    driver: bridge
